---
# file: mysql/tasks/configuration.yml
#
# configuration tasks.
#

- name: setup mysql profile for users
  template:
    src=home/user/.profile_mysql.j2
    dest="~{{ item }}/.profile_mysql{{ mysql_major_version }}{{ mysql_minor_version }}"
    owner="{{ item }}"
    group="staff"
    mode=0644
  become: yes
  with_items: "{{ mysql_users }}"

- name: ensure user environment gets load with mysql variables
  lineinfile:
    line="source ~/.profile_mysql{{ mysql_major_version }}{{ mysql_minor_version }}"
    dest="~{{ item }}/.profile"
    owner="{{ item }}"
    group="staff"
    mode=0644
  become: yes
  with_items: "{{ mysql_users }}"
