---
# file: mysql/tasks/debug.yml
#
# debug tasks.
#

- debug:
    var="{{ item }}"
  when: "{{ item }} is defined"
  with_items:
    - debug
    - ansible_os_family
    - ansible_os_distribution
    - mysql_version
    - mysql_major_version
    - mysql_minor_version
    - mysql_users
