---
# file: postgresql/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- name: include OS family/distribution specific tasks
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}/{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}/main.yml"
  tags: installation

- include: configuration.yml
  tags: configuration
