---
# file: postgresql/tasks/validation.yml
#
# validation tasks.
#

- name: ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - postgresql_version
    - postgresql_major_version
    - postgresql_minor_version
