---
# file: mysql/tasks/darwin/macosx.yml
#
# mysql tasks for Darwin/MacOSX.
#

- name: ensure the mysql server port is installed
  macports:
    name="{{ item }}"
    state=present
  become: yes
  notify: macosx | start mysql
  with_items:
    - "mysql{{ mysql_major_version }}{{ mysql_minor_version }}-server"
    - mysql_select

- name: ensure this version is the default mysql version
  command: "sudo port select --set mysql mysql{{ mysql_major_version }}{{ mysql_minor_version }}"
  when: mysql_set_default
  notify: macosx | start mysql
  become: yes
