---
# file: mysql/handlers/main.yml
#
# handlers file
#

- name: macosx | start mysql
  command: "port load mysql{{ mysql_major_version }}{{ mysql_minor_version }}-server"
  become: yes

- name: macosx | stop mysql
  command: "port unload mysql{{ mysql_major_version }}{{ mysql_minor_version }}-server"
  become: yes
